[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip ATSAM3X8E --speed 500"
rustflags = [
  "-C", "linker=flip-link",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
  # This is needed if your flash or ram addresses are not aligned to 0x10000 in memory.x
  # See https://github.com/rust-embedded/cortex-m-quickstart/pull/95
  # "-C", "link-arg=--nmagic",
]

[alias]
rb = "run --target thumbv7m-none-eabi -Zbuild-std=core --bin"
rrb = "run --target thumbv7m-none-eabi -Zbuild-std=core --release --bin"
bt = "build --target thumbv7m-none-eabi -Zbuild-std=core"
xtask = "run --manifest-path ./xtask/Cargo.toml --"
